CREATE DIONE_USER (ID SERIAL NOT NULL, EXTERNAL_ID TEXT, APP_TYPE TEXT, User_Age INTEGER, STATUS INTEGER);

CREATE DIONE_USER_CARD (DIONE_USER_ID INTEGER,DE2_CARD_NBR TEXT, PRIMARY KEY (DIONE_USER_ID,DE2_CARD_NBR));

CREATE TABLE DIONE_TXN_DETAILS(ID  SERIAL NOT NULL, TXNDATE TIMESTAMP WITH TIME ZONE, DE2_CARD_NBR TEXT NOT NULL, DW_MERCH_DBA TEXT NOT NULL,DW_MERCH_STATE_CD TEXT, DW_MERCH_CITY_NAME TEXT, CATEGORY TEXT NOT NULL, PRIMARY KEY (ID));

CREATE DIONE_USER_SUBSCRIPTIONS (ID SERIAL NOT NULL, DIONE_USER_ID INTEGER, EMAIL_ID TEXT, PHONE TEXT,NOTIFICATION_MODE TEXT,CATEGORY TEXT, STATUS INTEGER);

--Sample data (we can move to mock.sql)
INSERT INTO DIONE_USER (EXTERNAL_ID,APP_TYPE,User_Age,STATUS) VALUES ('joe.test3@email.com','MASTERPASS',35,1);
INSERT INTO DIONE_USER_CARD (DIONE_USER_ID,DE2_CARD_NBR) VALUES ('joe.test3@email.com','CARD_000001473047');
INSERT INTO DIONE_TXN_DETAILS (TXNDATE,DE2_CARD_NBR,DW_MERCH_DBA,DW_MERCH_STATE_CD,DW_MERCH_CITY_NAME,CATEGORY) VALUES (now(),'CARD_000001473047','MERCHANT_000000953004','VA','ALEXANDRIA','GAME');