CREATE DIONE_USER (ID SERIAL NOT NULL, EXTERNAL_ID TEXT, APP_TYPE TEXT, User_Age INTEGER, STATUS INTEGER);

CREATE DIONE_USER_CARD (DIONE_USER_ID INTEGER, );

CREATE TABLE DIONE_TXN_DETAILS(ID  SERIAL NOT NULL, TXNDATE TIMESTAMP WITH TIME ZONE, DE2_CARD_NBR TEXT NOT NULL, DW_MERCH_DBA TEXT NOT NULL,DW_MERCH_STATE_CD TEXT, DW_MERCH_CITY_NAME TEXT, CATEGORY TEXT NOT NULL, PRIMARY KEY (ID));

CREATE DIONE_USER_SUBSCRIPTIONS (ID SERIAL NOT NULL, DIONE_USER_ID INTEGER, EMAIL_ID TEXT, PHONE TEXT,NOTIFICATION_MODE TEXT,CATEGORY TEXT, STATUS INTEGER);

--Sample data (we can move to mock.sql)
INSERT INTO dione_txn_details (WALLET_ID,created_at,Merchant,Description,User_Age,update_at) VALUES ('XYZ001',now(),'Lucky','Grocery',32,now());